### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by axelgenus**
- Renamed root namespace.
- Updated package description and URL.
- Added XML documentation for the release target.
- Added Unity.Container dependency.

### CODE REVIEW

**Comment by ENikS** [comment]
If you not planning any more fixes I'll release this one on weekend.

**Comment by axelgenus** [comment]
I have nothing else planned. I should start working on ASP.NET MVC 6.

**Comment by ENikS** [comment]
I'll wait on this one than. Will release it once you are done.

**Comment by axelgenus** [comment]
Go ahead with this. MVC 6 seems a no-go.

**Pull request merged**
